const INVALID_GREENHOUSE_PLANT_ID 	= -1;
const MAX_GREENHOUSE_PLANTS 		= 10; 	// Максимальное количество растений в одной теплице

enum GREENHOUSE_PLANT {
	GREENHOUSE_PLANT_OBJECT_ID,
	GREENHOUSE_OBJECT_STATUS:GREENHOUSE_PLANT_OBJECT_STATUS,
	GREENHOUSE_PLANT_POSITION[Vector3D]
}

new g_Greenhouse_Plant[MAX_PLAYERS][MAX_PLAYER_GREENHOUSE][MAX_GREENHOUSE_PLANTS][GREENHOUSE_PLANT];