const MAX_CONFIG_VALUE_LENGTH = 64;

enum CONFIG {
	CONFIG_NAME[MAX_CONFIG_VALUE_LENGTH],
	CONFIG_DATABASE_HOST[MAX_CONFIG_VALUE_LENGTH],
	CONFIG_DATABASE_PORT,
	CONFIG_DATABASE_USER[MAX_CONFIG_VALUE_LENGTH],
	CONFIG_DATABASE_PASSWORD[MAX_CONFIG_VALUE_LENGTH],
	CONFIG_DATABASE_TABLE[MAX_CONFIG_VALUE_LENGTH],
	bool:CONFIG_DATABASE_AUTORECONNECT,
	CONFIG_DATABASE_CHARSET[MAX_CONFIG_VALUE_LENGTH]
}

new g_Config[CONFIG];