new const PLAYER_TABLE_NAME[] 	= "accounts";
const INVALID_PLAYER_UNIQUE_ID 	= -1;
const INVALID_PLAYER_ACCOUNT_ID = -1;

enum PLAYER {
	PLAYER_UNIQUE_ID,
	PLAYER_ACCOUNT_ID,
	PLAYER_LEVEL,
	PLAYER_EXP
}

new g_Player[MAX_PLAYERS][PLAYER] = {
	{
		INVALID_PLAYER_UNIQUE_ID, 	// PLAYER_UNIQUE_ID
		INVALID_PLAYER_ACCOUNT_ID,  // INVALID_PLAYER_ACCOUNT_ID
		1, 							// PLAYER_LEVEL
		0  							// PLAYER_EXP
	},
	...
};

new const PLAYER_EOS[PLAYER] = {
	INVALID_PLAYER_UNIQUE_ID, 		// PLAYER_UNIQUE_ID
	INVALID_PLAYER_ACCOUNT_ID,		// INVALID_PLAYER_ACCOUNT_ID
	1, 								// PLAYER_LEVEL
	0  								// PLAYER_EXP
};

new Iterator:g_iPlayer<MAX_PLAYERS>;