enum GREENHOUSE_TEST {
	GREENHOUSE_PRODUCT_TYPE:GREENHOUSE_TEST_PRODUCT,
	GREENHOUSE_TEST_SEEDS,
	bool:GREENHOUSE_TEST_IMPROVEMENTS[GREENHOUSE_IMPROVE],
	bool:GREENHOUSE_TEST_REGISTERED,
	GREENHOUSE_TEST_PROC_INTERVAL,
	GREENHOUSE_TEST_DISC_INTERVAL
}

new const g_Greenhouse_Test[GREENHOUSE_TEST] = {
	GREENHOUSE_PRODUCT_TYPE_TOMATO, 	// GREENHOUSE_TEST_PRODUCT
	5000,								// GREENHOUSE_TEST_SEEDS
	{ true },							// GREENHOUSE_TEST_IMPROVEMENTS
	true,								// GREENHOUSE_TEST_REGISTERED
	1000,								// GREENHOUSE_TEST_PROC_INTERVAL
	GREENHOUSE_HARVEST_INTERVAL * 1000 	// GREENHOUSE_TEST_DISC_INTERVAL
};